//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub username: String,
    pub password: String,
    #[sea_orm(unique)]
    pub email: Option<String>,
    pub avatar: Option<String>,
    pub display_name: Option<String>,
    #[sea_orm(unique)]
    pub display_user_id: Option<String>,
    pub email_verified: bool,
    pub disabled: bool,
    pub created_at: TimeDateTimeWithTimeZone,
    pub updated_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::mfa::Entity")]
    Mfa,
}

impl Related<super::mfa::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Mfa.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
