[http]
port = 19878

[internal]
auth_header = "x-internal-token"
auth_token = "replace-with-strong-internal-token"

[jwt]
issuer = "auth-server"
audience = "test"
key_dir = "config/key"
access_token_duration = 10800                                                                                                                       # 3 hours
refresh_token_duration = 604800                                                                                                                     # 1 week
access_key_validate_exp = true
refresh_key_validate_exp = true

[[db]]
name = "default"
url = "postgres://postgres:123456@localhost:15432/auth"
max_connections = 10
min_connections = 1
connect_timeout = 30
idle_timeout = 600
sql_logging = false

